//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Address { get; set; }
        public Nullable<long> ClassId { get; set; }
        public Nullable<long> StandardId { get; set; }
        public Nullable<long> EvaluationId { get; set; }
        public string AvatarImage { get; set; }
    }
}
